/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.google.gson.Gson

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    println("Belajar Kotlin")

    val gson = Gson()

    val product = Product("1","Handphone Ipun")
    println(StringUtil.toUpper(product.name))
}
